### PR TITLE
Generate a ~20hz interrupt using a software task

### PR DESCRIPTION
**Pull request by slacrherbst**
This PR implements a sw task which will trigger an interrupt at roughly ~20hz. This will ensure any stale buffers lingering in the write queue are pushed to hardware. This should address ESROGUE-444 where I theorize that a race condition stalls a write packet in the outbound queue without any interrupts to transfer it to the outbound hardware buffer.

### CODE REVIEW

**Comment by ruck314** [comment]
@slacrherbst: I am still getting the timeout error using this update for /cameralink-gateway:
```
ERROR:pyrogue.PollQueue:Block::checkTransaction: General Error: Transaction error for block ClinkDevRoot.ClinkFeb[0].PgpMon[1].TxClkFreqRaw with address 0x00406068. Error Timeout waiting for register transaction 141670 message response.
Traceback (most recent call last):
  File "/afs/slac.stanford.edu/g/reseng/vol26/anaconda/miniconda3/envs/rogue_pre-release/lib/python3.7/site-packages/pyrogue/_PollQueue.py", line 169, in _poll
    pr.checkTransaction(entry.block)
  File "/afs/slac.stanford.edu/g/reseng/vol26/anaconda/miniconda3/envs/rogue_pre-release/lib/python3.7/site-packages/pyrogue/_Block.py", line 29, in checkTransaction
    block._checkTransaction()
rogue.GeneralError: Block::checkTransaction: General Error: Transaction error for block ClinkDevRoot.ClinkFeb[0].PgpMon[1].TxClkFreqRaw with address 0x00406068. Error Timeout waiting for register transaction 141670 message response.
```
Here's my PCIe card config:
```
$ cat /proc/datadev_0
-------------- Axi Version ----------------
     Firmware Version : 0x4100000
           ScratchPad : 0x0
        Up Time Count : 893
            Device ID : 0x0
             Git Hash : 102fd2c976ffda9c3dea79a139f9013999d052a1
            DNA Value : 0x00000000400200010117f1801c50a085
         Build String : ClinkKcu1500Pgp2b: Vivado v2020.1, rdsrv314 (x86_64), Built Mon 11 Jan 2021 04:11:57 PM PST by ruckman

-------------- General HW -----------------
          Int Req Count : 0
        Hw Dma Wr Index : 4038
        Sw Dma Wr Index : 4038
        Hw Dma Rd Index : 2297
        Sw Dma Rd Index : 2297
     Missed Wr Requests : 0
       Missed IRQ Count : 386362
         Continue Count : 0
          Address Count : 4096
    Hw Write Buff Count : 256
     Hw Read Buff Count : 0
           Cache Config : 0x0
            Desc 128 En : 1
            Enable Ver  : 0x4010101
      Driver Load Count : 1
               IRQ Hold : 10000
              BG Enable : 0x0

-------------- General --------------------
          Dma Version : 0x5
          Git Version : 5.14.4-6-g3d17e21

-------------- Read Buffers ---------------
         Buffer Count : 256
          Buffer Size : 2097152
          Buffer Mode : 1
      Buffers In User : 0
        Buffers In Hw : 256
  Buffers In Pre-Hw Q : 0
  Buffers In Rx Queue : 0
      Missing Buffers : 0
       Min Buffer Use : 703
       Max Buffer Use : 704
       Avg Buffer Use : 703
       Tot Buffer Use : 180166

-------------- Write Buffers ---------------
         Buffer Count : 16
          Buffer Size : 2097152
          Buffer Mode : 1
      Buffers In User : 0
        Buffers In Hw : 0
  Buffers In Pre-Hw Q : 0
  Buffers In Sw Queue : 16
      Missing Buffers : 0
       Min Buffer Use : 11151
       Max Buffer Use : 11153
       Avg Buffer Use : 11151
       Tot Buffer Use : 178425
```

**Comment by ruck314** [comment]
Another observation, if I change my for loop from doing `root.LoadConfig(args.defaultFile)` (Writes & Reads) to `root.ReadAll()` (reads only) then I did not observe this issue with a loop of 10k (last for about 10mins):
```
        length = 10000
        with click.progressbar(
            length   = length,
            label    = click.style('Testing:  ', fg='green'),
        ) as bar:
            for i in range(length):
                root.ReadAll()
                bar.update(0x1)
            # Close the status bar
            bar.update(length) 
```

**Comment by ruck314** [comment]
Another observation, if I only loop with a `.set()` for only 1 register (no write then read queueing) than I do `NOT` observe the issue at looping for 10 minutes:
```
        length = 2**32
        with click.progressbar(
            length   = length,
            label    = click.style('Testing:  ', fg='green'),
        ) as bar:
            for i in range(length):
                root.ClinkFeb[0].AxiVersion.ScratchPad.set(i)
                if ( (i&0xFFF) == 0):
                    bar.update(0x1)
            # Close the status bar
            bar.update(length)  
```

**Comment by slacrherbst** [comment]
Ok. so this may not be the correct problem. I am lost at what to look at next. The symptom is that we get a packet stuck somewhere in the pipeline until a new packet is generated.

**Comment by ruck314** [comment]
Closing this PR because it does not fix the issue

**Comment by ruck314** [comment]
This patch didn’t fix the time stamp issue but resolved a stuck TX buffer issue (ESROGUE-489)

**Review by ruck314 — APPROVED** [review]

**Pull request merged**
