### PR TITLE
adding petalinux axi_stream_dma and axi_memory_map template

### PR DESCRIPTION
**Pull request by ruck314**
### Description
- Created to petalinux directory 
- Added petalinux/README.md for petalinux instructions
- Added axi_stream_dma petalinux template (similiar to rce_stream)
- Added axi_memory_map petalinux template (similiar to rce_memmap)

### CODE REVIEW

**Comment by ruck314** [comment]
Confirm that this works:
```bash
$ petalinux-build -c axistreamdma
[INFO] Sourcing buildtools
[INFO] Building axistreamdma
[INFO] Sourcing build environment
[INFO] Generating plnxtool conf
[INFO] Generating workspace directory
INFO: bitbake axistreamdma
NOTE: Started PRServer with DBfile: /u1/ruckman/build/petalinux/SpaceRfSocGen2_XC/build/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 41439, PID: 1194865
Loading cache: 100% |                                                                                                                                                                            | ETA:  --:--:--
Loaded 0 entries from dependency cache.
Parsing recipes: 100% |###########################################################################################################################################################################| Time: 0:00:23
Parsing of 3473 .bb files complete (0 cached, 3473 parsed). 5108 targets, 215 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
Initialising tasks: 100% |########################################################################################################################################################################| Time: 0:00:01
Sstate summary: Wanted 164 Found 118 Missed 46 Current 957 (71% match, 95% complete)
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 2970 tasks of which 2884 didn't need to be rerun and all succeeded.
INFO: Failed to copy built images to tftp dir: /tftpboot
[INFO] Successfully built axistreamdma
```

**Comment by ruck314** [comment]
Confirm the driver loads properly in petalinux after I figured out how to setup the device-tree and some other petalinux setting:
```bash
[    5.210675] axi_stream_dma: loading out-of-tree module taints kernel.
[    5.218609] axi_stream_dma: Probe: Using index 0 for axi_stream_dma_0.
[    5.225179] axi_stream_dma b0000000.axi_stream_dma_0: Init: Mapping Register space 0xb0000000 with size 0x10000.
[    5.235364] axi_stream_dma b0000000.axi_stream_dma_0: Init: Mapped to 0xffff800011880000.
[    5.243542] axi_stream_dma b0000000.axi_stream_dma_0: Init: Creating device class
[    5.251270] axi_stream_dma b0000000.axi_stream_dma_0: Init: Creating 8 TX Buffers. Size=16384 Bytes. Mode=1.
[    5.262297] axi_stream_dma b0000000.axi_stream_dma_0: Init: Created  8 out of 8 TX Buffers. 131072 Bytes.
[    5.271888] axi_stream_dma b0000000.axi_stream_dma_0: Init: Creating 8 RX Buffers. Size=16384 Bytes. Mode=1.
[    5.282304] axi_stream_dma b0000000.axi_stream_dma_0: Init: Created  8 out of 8 RX Buffers. 131072 Bytes.
[    5.292104] axi_stream_dma b0000000.axi_stream_dma_0: Init: Read  ring at: sw 0xffff8000118b9000 -> hw 0x6d140000.
[    5.302448] axi_stream_dma b0000000.axi_stream_dma_0: Init: Write ring at: sw 0xffff8000118ca000 -> hw 0x6d150000.
[    5.312819] axi_stream_dma b0000000.axi_stream_dma_0: Init: Found Version 2 Device. Desc128En=1
[    5.321515] axi_stream_dma b0000000.axi_stream_dma_0: Init: IRQ 48
```

**Comment by ruck314** [comment]
Here's the `cat proc`
```
-------------- General HW -----------------
          Int Req Count : 0
        Hw Dma Wr Index : 0
        Sw Dma Wr Index : 0
        Hw Dma Rd Index : 0
        Sw Dma Rd Index : 0
     Missed Wr Requests : 0
       Missed IRQ Count : 0
         Continue Count : 0
          Address Count : 4096
    Hw Write Buff Count : 8
     Hw Read Buff Count : 0
           Cache Config : 0x0
            Desc 128 En : 1
            Enable Ver  : 0x4010101
      Driver Load Count : 1
               IRQ Hold : 0
              BG Enable : 0x0

-------------- General --------------------
          Dma Version : 0x5
          Git Version : petalinux

-------------- Read Buffers ---------------
         Buffer Count : 8
          Buffer Size : 16384
          Buffer Mode : 1
      Buffers In User : 0
        Buffers In Hw : 8
  Buffers In Pre-Hw Q : 0
  Buffers In Rx Queue : 0
      Missing Buffers : 0
       Min Buffer Use : 0
       Max Buffer Use : 0
       Avg Buffer Use : 0
       Tot Buffer Use : 0
```

**Comment by ruck314** [comment]
Migrated rce_memmap (32-bit address) to new petalinux ax_memory_map (64-bit address support):

**Review by slacrherbst — APPROVED** [review]

**Pull request merged**
